---
- name: Instalation default Nginx
  hosts: all
  become: yes
  any_errors_fatal: yes
  
  vars:
    github_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63656132366339343966353337376665613833613337303234343365373730623838383031623930
          6464336339323937313134633763633039646437353865660a623264633238636564303839616336
          33356535303061333234383337356631663339646366313230653061323166333832616338623435
          3135346333373833620a396365613433663130373338313634383136353063643133343431333461
          3066
    mysql_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62356231383936363937383235343338653236653031333335333764356132386666323739383934
          3634333730323136393132343734643632333333303537360a393735333131373039663465313336
          35613566643466663930303464633264336664646565373466316435626465346437393765623436
          3232653965356664620a626561613866313930383564326630613832363831316539663831633036
          6332
   

  tasks:
  - name: Install nginx
    apt: name=nginx state=latest

  - name: make default enable service nginx
    service: name=nginx state=started enabled=yes 
  
  - name: install mysql-server
    apt: name=mysql-server state=latest 
  
#  - name: make default enable service mysql-server
#    service: name=mysql state=started enable=yes

  - name: create dir projects
    file: state=directory path=/home/ubuntu/projects

  - name: clone repozitory with project from git
    shell: git clone https://shchedrovmaxim:{{ github_pass }}@github.com/shchedrovmaxim/authentication_queue_bot /home/ubuntu/projects
  
  - name: create user in mysql-server
    shell: mysql -u root < /home/ubuntu/projects/mysql_scripts/create_user.sql 
  
  - name: create db queue
    shell: mysql -u root < /home/ubuntu/projects/mysql_scripts/create_database.sql

  - name: create tables in db
    shell: mysql -u root < /home/ubuntu/projects/mysql_scripts/create_tables.sql
   
  - name: install python3.7
    shell: | 
           add-apt-repository -y ppa:deadsnakes/ppa
           apt update
           apt install -y python3.7
   
  - name: install pip
    apt: name=python3-pip state=latest

  - name: install virtualenc in python 3.7
    shell: python3.7 -m pip install virtualenv

  - name: instal python3.7-dev for uwsgi
    apt: name=python3.7-dev state=latest
  
  - name: Create Python virtual env and install multiple packages inside the virtual env
    pip:
      requirements:  /home/ubuntu/projects/requriment.txt
      virtualenv:  /home/ubuntu/projects/venv
      virtualenv_python: /usr/bin/python3.7

  - name: Copy config to nginx
    copy: src=/home/ubuntu/projects/authentification_queue_bot.conf dest=/etc/nginx/sites-enabled remote_src=yes 
  
  - name: create dir for certificats
    file: state=directory path=/etc/letsencrypt/live/www.authentification-queue.pp.ua 

  - name: copy cert 
    copy: src=cert.pem dest=/etc/letsencrypt/live/www.authentification-queue.pp.ua/fullchain.pem 

  - name: copy key
    copy: src=key dest=/etc/letsencrypt/live/www.authentification-queue.pp.ua/privkey.pem 

  - name: Check NGINX configs
    shell: "/usr/sbin/nginx -t"
    register: nginx_config_status
  - name: NGINX test status
    debug:
      msg: "{{ nginx_config_status }}"
  - name: NGINX test status
    debug:
      msg: "{{ nginx_config_status.rc }}"


  - name: Restart nginx
    systemd:
      name: nginx
      state: restarted
      enabled: yes
      daemon_reload: yes
    when: nginx_config_status.rc == 0
    
#  - name: start app
#    shell: uwsgi --ini /home/ubuntu/projects/project.ini

