---
- name: Instalation default Nginx
  hosts: all
  become: yes

  tasks:
  - name: Install nginx
    apt: name=nginx state=latest

  - name: make default enable service nginx
    service: name=nginx state=started enabled=yes
